-- Query 1: Names of people who owned cars involved in accidents in 2008
SELECT P.D_NAME 
FROM PERSON P, PARTICIPATED P1, ACCIDENT A 
WHERE P.D_ID = P1.D_ID 
  AND P1.REPORT_NUM = A.REPORT_NUM 
  AND A.ACC_DATE LIKE '2008%';


-- Query 2: Name of owner and car model with maximum accidents in 2008
SELECT P.D_NAME, C.MODEL 
FROM PERSON P, CAR C, ACCIDENT A, PARTICIPATED P1 
WHERE P.D_ID = P1.D_ID 
  AND C.REG_NO = P1.REG_NO 
  AND A.REPORT_NUM = P1.REPORT_NUM 
  AND A.ACC_DATE LIKE '2008%' 
GROUP BY P.D_NAME, C.MODEL 
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*) 
    FROM PERSON P2, CAR C1, ACCIDENT A1, PARTICIPATED P4 
    WHERE P2.D_ID = P4.D_ID 
      AND C1.REG_NO = P4.REG_NO 
      AND A1.REPORT_NUM = P4.REPORT_NUM 
      AND A1.ACC_DATE LIKE '2008%' 
    GROUP BY P2.D_NAME, C1.MODEL
);


-- Query 3: Owners who own at least two TOYOTA cars (using 'A' as model per manual)
-- Pre-requisite: UPDATE CAR SET MODEL = 'A' WHERE REG_NO = '102';
SELECT P.D_NAME 
FROM PERSON P, CAR C, OWNS O 
WHERE P.D_ID = O.D_ID 
  AND C.REG_NO = O.REG_NO 
  AND C.MODEL = 'A' 
GROUP BY P.D_NAME 
HAVING COUNT(*) >= 2;


-- Query 4: Name of owner who owns the maximum number of TOYOTA cars
SELECT P.D_NAME, COUNT(*) AS NUM_OF_CARS 
FROM PERSON P, CAR C, OWNS O 
WHERE P.D_ID = O.D_ID 
  AND O.REG_NO = C.REG_NO 
  AND C.MODEL = 'A' 
GROUP BY P.D_NAME 
HAVING COUNT(*) >= ALL (
    SELECT COUNT(*) 
    FROM PERSON P1, CAR C1, OWNS O1 
    WHERE P1.D_ID = O1.D_ID 
      AND O1.REG_NO = C1.REG_NO 
      AND C1.MODEL = 'A' 
    GROUP BY P1.D_NAME
);


-- Query 5: Owner with minimum damage amount for accidents in 2008
SELECT P.D_NAME, SUM(P1.DAM_AMOUNT) 
FROM PERSON P, ACCIDENT A, PARTICIPATED P1 
WHERE P.D_ID = P1.D_ID 
  AND A.REPORT_NUM = P1.REPORT_NUM 
  AND A.ACC_DATE LIKE '2008%' 
GROUP BY P.D_NAME 
HAVING SUM(P1.DAM_AMOUNT) <= ALL (
    SELECT SUM(P4.DAM_AMOUNT) 
    FROM PERSON P2, ACCIDENT A1, PARTICIPATED P4 
    WHERE P2.D_ID = P4.D_ID 
      AND A1.REPORT_NUM = P4.REPORT_NUM 
      AND A1.ACC_DATE LIKE '2008%' 
    GROUP BY P2.D_NAME
);