-- 1. PERSON Table
CREATE TABLE PERSON (
    D_ID VARCHAR(10) PRIMARY KEY,
    D_NAME VARCHAR(25) NOT NULL,
    ADDR VARCHAR(30)
);


-- 2. CAR Table
CREATE TABLE CAR (
    REG_NO VARCHAR(10) PRIMARY KEY,
    MODEL VARCHAR(10) NOT NULL,
    YEAR DATE
);


-- 3. ACCIDENT Table
CREATE TABLE ACCIDENT (
    REPORT_NUM INT PRIMARY KEY,
    ACC_DATE DATE,
    ACC_LOC VARCHAR(30)
);


-- 4. OWNS Table
CREATE TABLE OWNS (
    D_ID VARCHAR(10) REFERENCES PERSON(D_ID),
    REG_NO VARCHAR(10) REFERENCES CAR(REG_NO),
    PRIMARY KEY (D_ID, REG_NO)
);


-- 5. PARTICIPATED Table
CREATE TABLE PARTICIPATED (
    D_ID VARCHAR(10) REFERENCES PERSON(D_ID),
    REG_NO VARCHAR(10) REFERENCES CAR(REG_NO),
    REPORT_NUM INT REFERENCES ACCIDENT(REPORT_NUM),
    DAM_AMOUNT INT,
    PRIMARY KEY (D_ID, REG_NO, REPORT_NUM)
);