-- 1. PUBLISHER Table
CREATE TABLE PUBLISHER (
    NAME VARCHAR(20) PRIMARY KEY,
    ADDRESS VARCHAR(30),
    PHONE VARCHAR(10)
);

-- 2. BOOK Table
CREATE TABLE BOOK (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(30),
    PUBLISHER_NAME VARCHAR(20) REFERENCES PUBLISHER(NAME) ON DELETE CASCADE,
    PUB_YEAR INT
);

-- 3. BOOK_AUTHORS Table
CREATE TABLE BOOK_AUTHORS (
    BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    AUTHOR_NAME VARCHAR(20),
    PRIMARY KEY (BOOK_ID, AUTHOR_NAME)
);

-- 4. LIBRARY_BRANCH Table
CREATE TABLE LIBRARY_BRANCH (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(20),
    ADDRESS VARCHAR(30)
);

-- 5. BOOK_COPIES Table
CREATE TABLE BOOK_COPIES (
    BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    BRANCH_ID INT REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON DELETE CASCADE,
    NO_OF_COPIES INT,
    PRIMARY KEY (BOOK_ID, BRANCH_ID)
);

-- 6. CARD Table (Borrowers)
CREATE TABLE CARD (
    CARD_NO INT PRIMARY KEY
);

-- 7. BOOK_LENDING Table
CREATE TABLE BOOK_LENDING (
    BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    BRANCH_ID INT REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON DELETE CASCADE,
    CARD_NO INT REFERENCES CARD(CARD_NO) ON DELETE CASCADE,
    DATE_OUT DATE,
    DUE_DATE DATE,
    PRIMARY KEY (BOOK_ID, BRANCH_ID, CARD_NO)
);