Create database ORDERS;
use ORDERS;

-- 1. CUSTOMER Table
CREATE TABLE CUSTOMER (
    CUST_NO INT PRIMARY KEY,
    CNAME VARCHAR(20) NOT NULL,
    CITY VARCHAR(20)
);


-- 2. ORDER Table
CREATE TABLE ORDERS (
    ORDER_NO INT PRIMARY KEY,
    ORDER_DATE DATE,
    CUST_NO INT REFERENCES CUSTOMER(CUST_NO),
    ORDER_AMT INT
);


-- 3. ITEM Table
CREATE TABLE ITEM (
    ITEM_NO INT PRIMARY KEY,
    UNITPRICE INT
);


-- 4. ORDER_ITEM Table (Linking Orders to Items)
CREATE TABLE ORDER_ITEM (
    ORDER_NO INT REFERENCES ORDERS(ORDER_NO),
    ITEM_NO INT REFERENCES ITEM(ITEM_NO),
    QTY INT,
    PRIMARY KEY (ORDER_NO, ITEM_NO)
);


-- 5. WAREHOUSE Table
CREATE TABLE WAREHOUSE (
    WAREHOUSE_NO INT PRIMARY KEY,
    CITY VARCHAR(20)
);


-- 6. SHIPMENT Table
CREATE TABLE SHIPMENT (
    ORDER_NO INT REFERENCES ORDERS(ORDER_NO),
    WAREHOUSE_NO INT REFERENCES WAREHOUSE(WAREHOUSE_NO),
    SHIP_DATE DATE,
    PRIMARY KEY (ORDER_NO, WAREHOUSE_NO)
);